#Aula 1


Chegou a hora de pôr em prática tudo o que aprendemos durante as aulas. Preparei dois projetos extras para desenvolvermos durante o curso, para garantir que possamos praticar bastante! Para isso, vamos trabalhar com 2 novos conjuntos de dados, mas que dessa vez serão bem menores. As bases de dados estão disponíveis para download abaixo:

    Projeto desafio 1: vendas online - dados_vendas_clientes.json;
    Projeto desafio 2: administração de condomínios - dados_locacao_imoveis.json.

Em cada aula, desenvolveremos uma etapa dos projetos. Portanto, salve seu código de construção em cada desafio para que possa aplicá-lo nos desafios posteriores.
Etapa 1

    Projeto desafio 1: vendas online

O objetivo desse projeto é realizar uma análise dos resultados de um evento com os clientes de uma empresa de vendas online. Foi coletado um conjunto de dados que contém os clientes que mais gastaram com produtos dentro de 5 dias de vendas, que é o período de duração do evento. Essa análise vai identificar o cliente com a maior compra na semana, que irá receber um prêmio da loja, e posteriormente, ela pode ajudar a empresa a criar novas estratégias para atrair mais clientes.

A base de dados utilizada nessa análise é a dados_vendas_clientes.json e contém informações importantes sobre os clientes como, o nome de cadastro do cliente, o valor total pago na compra e o dia da compra.

Sabendo essas informações, o desafio do projeto 1: vendas online será abrir a base de dados com Pandas e aplicar o json_normalize.

In [ ]:
import pandas as pd

dados_vendas_clientes = pd.read_json('/content/drive/MyDrive/Alura/DataScience/Pandas: transformação e manipulação de dados/dados_vendas_clientes.json')

In [ ]:
dados_vendas_clientes = pd.json_normalize(dados_vendas_clientes['dados_vendas'])
dados_vendas_clientes

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"
3,09/06/2022,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...","[R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]"
4,10/06/2022,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...","[R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]"

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"
3,B202 (blocoAP),"[04/06/2022, 04/07/2022]","[07/06/2022, 05/07/2022]","[$ 1300,0 reais, $ 2800,0 reais]"
4,C301 (blocoAP),"[05/06/2022, 05/07/2022]","[10/06/2022, 09/07/2022]","[$ 1400,0 reais, $ 2900,0 reais]"
5,C302 (blocoAP),"[06/06/2022, 06/07/2022]","[08/06/2022, 12/07/2022]","[$ 1500,0 reais, $ 1200,0 reais]"
6,D401 (blocoAP),"[07/06/2022, 07/07/2022]","[07/06/2022, 09/07/2022]","[$ 1600,0 reais, $ 1300,0 reais]"
7,D402 (blocoAP),"[08/06/2022, 08/07/2022]","[10/06/2022, 14/07/2022]","[$ 1700,0 reais, $ 1400,0 reais]"
8,E501 (blocoAP),"[09/06/2022, 09/07/2022]","[10/06/2022, 09/07/2022]","[$ 1800,0 reais, $ 1500,0 reais]"
9,E502 (blocoAP),"[10/06/2022, 10/07/2022]","[16/06/2022, 12/07/2022]","[$ 1900,0 reais, $ 1600,0 reais]"
10,F601 (blocoAP),"[11/06/2022, 11/07/2022]","[17/06/2022, 13/07/2022]","[$ 2000,0 reais, $ 1000,0 reais]"
11,F602 (blocoAP),"[12/06/2022, 12/07/2022]","[15/06/2022, 12/07/2022]","[$ 2100,0 reais, $ 1100,0 reais]"
12,G701 (blocoAP),"[13/06/2022, 13/07/2022]","[19/06/2022, 20/07/2022]","[$ 2200,0 reais, $ 1200,0 reais]"
13,G702 (blocoAP),"[14/06/2022, 14/07/2022]","[15/06/2022, 17/07/2022]","[$ 2300,0 reais, $ 2100,0 reais]"
14,H801 (blocoAP),"[15/06/2022, 15/07/2022]","[18/06/2022, 16/07/2022]","[$ 2400,0 reais, $ 2200,0 reais]"

In [ ]:
#remover os dados em listas dentro df

colunasVendasOnline = list(dados_vendas_clientes.columns)
colunasVendasOnline

['Data de venda', 'Cliente', 'Valor da compra']

In [ ]:
dados_vendas_clientes = dados_vendas_clientes.explode(colunasVendasOnline[1:])
dados_vendas_clientes.reset_index(drop=True, inplace=True)
dados_vendas_clientes

   Data de venda             Cliente Valor da compra
0     06/06/2022     @ANA _LUCIA 321        R$ 836,5
1     06/06/2022  DieGO ARMANDIU 210       R$ 573,33
2     06/06/2022  DieGO ARMANDIU 210        R$ 392,8
3     06/06/2022  DieGO ARMANDIU 210       R$ 512,34
4     07/06/2022  Isabely JOanes 738       R$ 825,31
5     07/06/2022  Isabely JOanes 738       R$ 168,07
6     07/06/2022  Isabely JOanes 738       R$ 339,18
7     07/06/2022  Isabely JOanes 738       R$ 314,69
8     08/06/2022  Isabely JOanes 738       R$ 682,05
9     08/06/2022    JOãO Gabriel 671       R$ 386,34
10    08/06/2022  Julya meireles 914       R$ 622,65
11    08/06/2022  Julya meireles 914       R$ 630,79
12    09/06/2022  Julya meireles 914        R$ 390,3
13    09/06/2022     MaRIA Julia 444       R$ 759,16
14    09/06/2022     MaRIA Julia 444       R$ 334,47
15    09/06/2022     MaRIA Julia 444       R$ 678,78
16    10/06/2022     MaRIA Julia 444       R$ 314,24
17    10/06/2022     PEDRO PASCO 812       R$ 311,15
18    10/06/2022    Paulo castro 481       R$ 899,16
19    10/06/2022   Thiago fritzz 883       R$ 885,24

In [ ]:
dados_vendas_clientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     object
dtypes: object(3)
memory usage: 608.0+ bytes

In [ ]:
dados_vendas_clientes['Valor da compra']

0      R$ 836,5
1     R$ 573,33
2      R$ 392,8
3     R$ 512,34
4     R$ 825,31
5     R$ 168,07
6     R$ 339,18
7     R$ 314,69
8     R$ 682,05
9     R$ 386,34
10    R$ 622,65
11    R$ 630,79
12     R$ 390,3
13    R$ 759,16
14    R$ 334,47
15    R$ 678,78
16    R$ 314,24
17    R$ 311,15
18    R$ 899,16
19    R$ 885,24
Name: Valor da compra, dtype: object

In [ ]:
import numpy as np

dados_vendas_clientes['Valor da compra'] = dados_vendas_clientes['Valor da compra'].apply(lambda x: x.replace('R', ' ').replace('$', '').replace(',', '.').strip()).astype(float)
dados_vendas_clientes

   Data de venda             Cliente  Valor da compra
0     06/06/2022     @ANA _LUCIA 321           836.50
1     06/06/2022  DieGO ARMANDIU 210           573.33
2     06/06/2022  DieGO ARMANDIU 210           392.80
3     06/06/2022  DieGO ARMANDIU 210           512.34
4     07/06/2022  Isabely JOanes 738           825.31
5     07/06/2022  Isabely JOanes 738           168.07
6     07/06/2022  Isabely JOanes 738           339.18
7     07/06/2022  Isabely JOanes 738           314.69
8     08/06/2022  Isabely JOanes 738           682.05
9     08/06/2022    JOãO Gabriel 671           386.34
10    08/06/2022  Julya meireles 914           622.65
11    08/06/2022  Julya meireles 914           630.79
12    09/06/2022  Julya meireles 914           390.30
13    09/06/2022     MaRIA Julia 444           759.16
14    09/06/2022     MaRIA Julia 444           334.47
15    09/06/2022     MaRIA Julia 444           678.78
16    10/06/2022     MaRIA Julia 444           314.24
17    10/06/2022     PEDRO PASCO 812           311.15
18    10/06/2022    Paulo castro 481           899.16
19    10/06/2022   Thiago fritzz 883           885.24

In [ ]:
dados_vendas_clientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float64
dtypes: float64(1), object(2)
memory usage: 608.0+ bytes

In [ ]:
#Sabendo disso, manipule os textos presentes na coluna Cliente para
#que seja obtido como resultado os nomes dos clientes em letras minúsculas, com a ausência de caracteres especiais ou números

dados_vendas_clientes['Cliente'] = dados_vendas_clientes['Cliente'].str.lower()
dados_vendas_clientes['Cliente'] = dados_vendas_clientes['Cliente'].replace('[^a-z]', '', regex=True).str.strip()
dados_vendas_clientes['Cliente']

0          analucia
1     diegoarmandiu
2     diegoarmandiu
3     diegoarmandiu
4     isabelyjoanes
5     isabelyjoanes
6     isabelyjoanes
7     isabelyjoanes
8     isabelyjoanes
9        joogabriel
10    julyameireles
11    julyameireles
12    julyameireles
13       mariajulia
14       mariajulia
15       mariajulia
16       mariajulia
17       pedropasco
18      paulocastro
19     thiagofritzz
Name: Cliente, dtype: object

In [ ]:
dados_vendas_clientes['Data de venda'] = pd.to_datetime(dados_vendas_clientes['Data de venda'], format= '%d/%m/%Y')
dados_vendas_clientes['Data de venda']

total_em_compras = dados_vendas_clientes.groupby('Cliente')['Valor da compra'].sum()
total_em_compras

Cliente
analucia          836.50
diegoarmandiu    1478.47
isabelyjoanes    2329.30
joogabriel        386.34
julyameireles    1643.74
mariajulia       2086.65
paulocastro       899.16
pedropasco        311.15
thiagofritzz      885.24
Name: Valor da compra, dtype: float64